=== mpashka/logdigger/src/log-format.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.i-vortex.com/log-format"
            xmlns="http://www.i-vortex.com/log-format"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">

    <xsd:element name="format" type="formatType"/>

    <xsd:complexType name="formatType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string" minOccurs="0"/>
            <xsd:element name="pattern" type="xsd:string"/>
            <xsd:element name="column" type="columnType" maxOccurs="unbounded"/>
            <xsd:element name="message-column" type="messageColumnType"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="columnType">
        <xsd:sequence>
            <xsd:element name="highlight" type="hlType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="group" type="xsd:positiveInteger" use="required"/>
        <xsd:attribute name="indexable" type="xsd:boolean" use="optional" default="false"/>
    </xsd:complexType>

    <xsd:complexType name="messageColumnType">
        <xsd:attribute name="name" type="xsd:string" use="optional" default="Message"/>
        <xsd:attribute name="group" type="xsd:positiveInteger" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="hlType">
        <xsd:attribute name="value" type="xsd:string" use="required"/>
        <xsd:attribute name="color" type="xsd:string" use="required"/>
    </xsd:complexType>

</xsd:schema>

=== mpashka/logdigger/xml/sleeNew.xml
<?xml version="1.0" encoding="UTF-8"?>

<format xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.i-vortex.com/log-format"
        xsi:schemaLocation="http://www.i-vortex.com/log-format log-format.xsd">
    <name>SLEE-NEW</name>
    <pattern>
        <![CDATA[^\d{4}-\d{2}-\d{2}\s+(\w+)\s+([\w\._\-\|]+)\s+\[\s*(.+?)\]\s+(\d{2}:\d{2}:\d{2}[\.\,]\d{3})\s+\:\s+(.*)$]]>
    </pattern>
    <column name="Time" group="4"/>
    <column name="Level" group="1" indexable="true">
        <highlight value="ERROR" color="0xff0000"/>
        <highlight value="WARN" color="0x0000ff"/>
    </column>
    <column name="Category" group="2" indexable="true"/>
    <column name="Thread" group="3" indexable="true"/>
    <message-column name="Message" group="5"/>
</format>

=== mpashka/logdigger/trunk/xml/test.xml
<?xml version="1.0" encoding="UTF-8"?>

<format xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.i-vortex.com/log-format"
        xsi:schemaLocation="http://www.i-vortex.com/log-format log-format.xsd">
    <name>SMP</name>
    <pattern>
        <![CDATA[^(\d{2}:\d{2}:\d{2}\,\d{3})\s+\[(.+)\]\s+(\w+)\s+([\w-\.]+)\s+:\s+(.*)$]]>
    </pattern>
    <column name="Time" group="1"/>
    <column name="Level" group="3" indexable="true">
        <highlight value="ERROR" color="0xff0000"/>
        <highlight value="WARN" color="0x0000ff"/>
    </column>
    <column name="Category" group="4" indexable="true"/>
    <column name="Thread" group="2" indexable="true"/>
    <message-column group="5"/>
</format>

=== mpashka/logdigger/trunk/xml/slee.xml
<?xml version="1.0" encoding="UTF-8"?>

<format xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.i-vortex.com/log-format"
        xsi:schemaLocation="http://www.i-vortex.com/log-format log-format.xsd">
    <name>SLEE</name>
    <pattern>
        <![CDATA[^\d{4}-\d{2}-\d{2}\s(\d{2}:\d{2}:\d{2}[\.\,]\d{3})\s+\[\s*(.+?)\]\s+(\w+)\s+([^\s]+)\s+:\s+(.*)$]]>
    </pattern>
    <column name="Time" group="1"/>
    <column name="Thread" group="2" indexable="true"/>
    <column name="Level" group="3" indexable="true">
        <highlight value="ERROR" color="0xff0000"/>
        <highlight value="WARN" color="0x0000ff"/>
    </column>
    <column name="Category" group="4" indexable="true"/>
    <message-column group="5"/>
</format>

=== mpashka/logdigger/trunk/xml/glassfish.xml
<?xml version="1.0" encoding="UTF-8"?>

<format xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.i-vortex.com/log-format"
        xsi:schemaLocation="http://www.i-vortex.com/log-format log-format.xsd">
    <name>Glassfish</name>
<!--
[#|2009-07-08T17:48:34.300+0400|INFO|glassfish|null|_ThreadID=14;_ThreadName=Thread-1;|felix.fileinstall.debug          1|#]
        <![CDATA[(?s)^[#\|\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}[+-]\d{3}\|(\p{Upper}+)\|\s+([\w\._\-\|]+)\s+\[\s*(.+?)\]\s+(\d{2}:\d{2}:\d{2}[\.\,]\d{3})\s+\:\s+(.*)$]]>
-->
    <pattern>
        <![CDATA[(?s)\[#\|.{11}(.{12})[^|]+\|([^|]+)\|([^|]+)\|([^|]+)\|_ThreadID=(\d+);_ThreadName=([^;]+);([^|]*)?\|([^|\n]*)(?:\|#\])?]]>
    </pattern>
    <column name="Time" group="1"/>
    <column name="Level" group="2" indexable="true">
        <highlight value="ERROR" color="0xff0000"/>
        <highlight value="WARN" color="0x0000ff"/>
    </column>
    <column name="Category" group="4" indexable="true"/>
    <column name="ThreadID" group="5" indexable="true"/>
    <column name="Thread" group="6" indexable="true"/>
    <column name="ClassInfo" group="7" indexable="true"/>
    <message-column name="Message" group="8"/>
</format>
